### ISSUE TITLE
Unclear when to use &j.x or j.x

### ISSUE THREAD

**Issue by oryband** [gima/jsonv#3]
It isn't clean when to use `&` `&j.String{..}` and `j.ObjectEach{..}`. This should be clarified.

In addition, perhaps there's a way to avoid this ugly `&j.` prefixes?

**Comment by gima** [comment]
After dissecting these issues, the core problem seemed to be that the jsonv didn't have such a great architechture. I wrote it in my early days with golang, and thus I decided to (for better or worse) create a new version of json, cleverly named jsonv2. Because the new API is somewhat different, I placed it in a new repository (spirit remains the same).

The new version is available at: https://github.com/gima/jsonv2

Regarding the need for better documentation: Does it seem that the new version bears the same problem? I tried to make the API design cleaner and more readily extensible.

Other than that, from my point of view the issues that you have opened have been fixed in the new library. What do you think, does it solve the problems?

#### Comments on the issues that you have raised:

> #8 all exported (public) struct members should have a verbose variable name 

New library design does not expose structs.

> #6 add j.ObjectKey (like j.ObjectItem)

Done: `j.ObjKeys()`

> #5  add support for more than 2 'or's and more than 2 'and's

Both `j.And()` and `j.Or()` support any amount of Validators.

> #4  how to unmarshal something which is not interface{}?

The new documentation [states](https://godoc.org/github.com/gima/jsonv2) which data types the supplied validators understand. The library is not tied to json in any way, but can validate the output of `JSON.Unmarshal` just like before.

> #3 Unclear when to use &j.x or j.x

Not a problem anymore, since the supplied validators are not structs, but functions. (Only one way to use them.)

**Comment by oryband** [comment]
Wow @gima , that's amazing! Great job!

Yes, it looks you took care of everything. I would in the future migrate my code from jsonv1 to jsonv2 and validate (haha) that everything indeed does work well.

Btw, I'm not sure that creating a new *jsonv2* repo is a good idiom. Perhaps just create two subdirectories in here, called `v1/` and `v2/` with the new codebase in `v2/`. Thus I can choose which version to use by appending a directory to the import path.

If you don't like this, that's also fine - just don't forget to mention in the README that this repo is deprecated and redirect to new repo.

**Comment by oryband** [comment]
You can close all issues and redirect to jsonv2 as far as I'm concerned.

**Comment by oryband** [comment]
Oh and one more thing - I found this repo by search for a python [voluptouous][vol] equivalent (my main language). It might be worth writing in the front page README (and docs) to what jsonv is trying to be similar too:
- Python: [Voluptouous][vol] and [json_schema](https://pypi.python.org/pypi/json_schema)
- Ruby: [json-schema](https://github.com/ruby-json-schema/json-schema)
- JS: [jsonvalidator](https://code.google.com/p/jsonvalidator/)
- Other languages

This could help people feel comfortable and welcomed to the library - by letting them know they have found an equivalent of something popular they know from their other languages.

[vol]: https://pypi.python.org/pypi/voluptuous

**Comment by gima** [comment]
Thank you. I will do these.

**Comment by gima** [comment]
Weird. I thought I had written this reply already.

> Btw, I'm not sure that creating a new jsonv2 repo is a good idiom ...

Nice! Damn. Why didn't I think of this. I even contemplated on using http://gopkg.in/ but decided against it because of unnecessary dependency

I have opted to use the the v1,v2,.. subdirectory structure for the project.

I couldn't use the jsonv repository, as I wanted the code that depended on jsonv to remain working (I wrote a note about replacement). Also mixing this new versioning strategy would have been a little messy since the original version didn't use this versioning strategy

Unfortunately this required a rename of the rewrite, as the name "jsonv2" didn't exactly stand well with the subdirectory versioning. *(I dumbly just hoped that you or anyone else for that matter hadn't already used the new library. Apologies if this caused problems.)*

> Oh and one more thing - I found this repo by search for a python voluptouous equivalent ...

Good idea. I added the ones you mentioned (and maybe a bit unnecessarily one for golang), plus search keywords to the front page.

---

Oh, and the repository is https://github.com/gima/govalid  
Thank you once again. The amazing job -part cheered me up ^_^

**Comment by oryband** [comment]
also, you can check what [elastigo](https://github.com/mattbaird/elastigo) did - they just tagged the last commit of the old version with 'v1' and started working on v2. They recommend use go dep for using the old version. Just another solution - your call of course.
